// <auto-generated />
using System;
using Hospitales.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospitales.Migrations
{
    [DbContext(typeof(HospitalesContext))]
    [Migration("20230507202602_fixInDelete")]
    partial class fixInDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("parcial1_hospitales.Models.Doctor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("hospitalId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("specialty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("hospitalId");

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("parcial1_hospitales.Models.Hospital", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("address")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Hospital");
                });

            modelBuilder.Entity("parcial1_hospitales.Models.Doctor", b =>
                {
                    b.HasOne("parcial1_hospitales.Models.Hospital", "hospital")
                        .WithMany("Doctors")
                        .HasForeignKey("hospitalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("hospital");
                });

            modelBuilder.Entity("parcial1_hospitales.Models.Hospital", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
